config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  # resources :kittens, only: [:index, :create, :show]
  
  get '/kittens', to: 'kittens#index'
  #need a form to create a new kitten so use the "new" action.
  #/kittens/new needs to be above /:id because Ruby reads top to bottom and will hit /:id first and error.
  get '/kittens/new', to: 'kittens#new'
  get '/kittens/:id', to: 'kittens#show', as: 'kitten'
  post '/kittens', to: 'kittens#create'

  get '/people', to: 'people#index', as: 'people'
  get '/people/:id', to: 'people#show', as: 'person'

  get '/playdates/new', to: 'playdates#new', as: 'new_playdate'
  post '/playdates', to: 'playdates#create'
  
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord 
  has_many :playdates
  has_many :people, through: :playdates

  validates :name, :age, :breed, :personality, :image,  presence: true
end

app/models/person.rb
class Person < ApplicationRecord
  has_many :playdates
  has_many :kittens, through: :playdates
end

app/models/playdate.rb
class Playdate < ApplicationRecord
  belongs_to :kitten
  belongs_to :person 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all
  end

  def show
    @kitten = Kitten.find(params[:id])
    #byebug
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.create(kitten_params)
    #byebug
    redirect_to kitten_path(@kitten)
  end

  def kitten_params
    params.require(:kitten).permit(:name, :age, :breed, :personality, :image)
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
  end

  def show
    @person = Person.find(params[:id])
  end
end

app/controllers/playdates_controller.rb
class PlaydatesController < ApplicationController
  def new
    @playdate = Playdate.new
  end

  def create 

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/playdates_helper.rb
module PlaydatesHelper
end

app/views/kittens/index.html.erb
<h1>This is my cats index page </h1>

<ul>
  <% @kittens.each do | k | %>
  
    <li>  <%= link_to k.name, kitten_path(k)%> </li>
  
  <% end %>
</ul>
<br/>
<h4>To Add a New Kitten to be available for adoption through Playdates Click "New Kitten Form" Below.</h4>
<%= link_to "New Kitten Form", kittens_new_path %>

app/views/kittens/new.html.erb
<h1>This should be the kittens/new page</h1>


<%= form_for @kitten do | f | %>
  <%= f.label :name %>:
  <%= f.text_field :name %>
  <br/>
  <br/>
  <%= f.label :age %>:
  <%= f.number_field :age %>
  <br/>
  <br/>
  <%= f.label :breed %>:
  <%= f.text_field :breed %>
  <br/>
  <br/>
  <%= f.label :personality%>:
  <%= f.text_field :personality %>
  <br/>
  <br/>
  <%= f.label :image_link%>:
  <%= f.text_field :image%>
  <br/>
  <br/>
  <%= f.submit %>
<%end%>
<br/>
<h4>To Cancel Adding a New Kitten to Available Adoptions through Playdates Click "Cancel" Below.</h4>
<%= link_to "Cancel", kittens_path %>

app/views/kittens/show.html.erb
<h1>Book a time to meet with <%= @kitten.name %>.</h1>
<hr>
<br/>
<img src=<%= @kitten.image %> alt="Image of a kitten" style="width:160px;height:160px;">
<h2>Name: <%= @kitten.name %> </h2>
<h2>Age: <%= @kitten.age %> </h2>
<h2>Breed: <%= @kitten.breed %> </h2>
<h2>Personality: <%= @kitten.personality %> </h2>
<br/>
<%= link_to "All Kittens", kittens_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Adopt A Kitten Playdate</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/index.html.erb
<H1>This is my people index page</h1>

<ul>
  <% @people.each do | person | %>
  
    <li> <%= link_to person.name, person_path(person) %> </li>
  
  <% end %>
</ul>

app/views/people/show.html.erb
<h1>This is my Person Show page</h1>
<h2> <%= @person.name %> </h2>
<hr/>
<br/>
<h3> These are <%= @person.name %>'s playdates in the future: </h3>
  <% @person.playdates.each do | pd | %>
   <li> <%= pd.date %> : <%= pd.length_of_time %> minutes with <%= link_to pd.kitten.name, kitten_path(pd.kitten) %> </li>
    <br/>
  <% end %>

app/views/playdates/new.html.erb
<h1>New Playdate Form Page</h1>
<hr>
<%= form_for @playdate do | f | %>
<%= f.label :date %> ('mm-dd-yyyy'):
<%= f.text_field :date %>
<br/>
<br/>
<%= f.label :time%> (in minutes):
<%= f.number_field :length_of_time %>
<br/>
<br/>
<%= f.submit %> 
<% end %>